# Generated by Django 5.1.1 on 2026-01-03 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del contenido')),
                ('descripcion', models.TextField(verbose_name='Descripción del contenido')),
                ('contenido_tema', models.TextField(verbose_name='Contenido del tema')),
                ('materia', models.CharField(max_length=100, verbose_name='Materia')),
                ('nivel_curso', models.CharField(max_length=100, verbose_name='Nivel/Curso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado')),
                ('publicacion', models.CharField(choices=[('publicado', 'Publicado'), ('no_publicado', 'No Publicado')], default='no_publicado', max_length=20, verbose_name='Publicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de última edición')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos_creados', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos_editados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VideoContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.URLField(max_length=500, verbose_name='Enlace del video')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='contenido.contenido')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['orden'],
            },
        ),
    ]
