# Generated by Django 5.1.1 on 2026-01-03 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'ordering': ['orden', '-fecha_creacion'], 'verbose_name': 'Contenido', 'verbose_name_plural': 'Contenidos'},
        ),
        migrations.AddField(
            model_name='contenido',
            name='es_obligatorio',
            field=models.BooleanField(default=True, verbose_name='Es obligatorio completar'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Define la secuencia del contenido', verbose_name='Orden en el curso'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='prerequisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos_siguientes', to='contenido.contenido', verbose_name='Contenido prerequisito'),
        ),
        migrations.CreateModel(
            name='ProgresoContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('porcentaje_avance', models.PositiveIntegerField(default=0, verbose_name='Porcentaje de avance')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='contenido.contenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de contenido',
                'verbose_name_plural': 'Progresos de contenidos',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('usuario', 'contenido')},
            },
        ),
    ]
