# Generated by Django 5.1.1 on 2026-01-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_alter_contenido_options_contenido_es_obligatorio_and_more'),
        ('temas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='materia',
            new_name='tema',
        ),
        migrations.AlterField(
            model_name='contenido',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temas.tema', verbose_name='Tema'),
        ),
    ]
