# Generated by Django 5.1.1 on 2026-01-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_alter_contenido_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='tipo_contenido',
            field=models.CharField(choices=[('universitario', 'Universitario'), ('postulante', 'Postulante')], default='universitario', max_length=20, verbose_name='Tipo de contenido'),
        ),
    ]
