# Generated by Django 5.1.1 on 2026-01-05 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MazoPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mazos_premium_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mazo Premium',
                'verbose_name_plural': 'Mazos Premium',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proximo_repaso', models.DateTimeField(default=django.utils.timezone.now)),
                ('intervalo', models.IntegerField(default=0)),
                ('factor_facilidad', models.FloatField(default=2.5)),
                ('repeticiones', models.IntegerField(default=0)),
                ('ultimo_repaso', models.DateTimeField(blank=True, null=True)),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='flashcards_premium.mazopremium')),
            ],
            options={
                'verbose_name': 'Flashcard Premium',
                'verbose_name_plural': 'Flashcards Premium',
                'ordering': ['proximo_repaso'],
            },
        ),
    ]
