# Generated by Django 5.1.1 on 2026-01-05 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Examen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('duracion_minutos', models.IntegerField(default=60, verbose_name='Duración (minutos)')),
                ('es_premium', models.BooleanField(default=True, verbose_name='Requiere Suscripción Premium')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='temas.tema', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la Pregunta')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1, verbose_name='Letra de la Opción')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='Es Correcta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['letra'],
            },
        ),
        migrations.CreateModel(
            name='Enunciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número del Enunciado')),
                ('texto', models.TextField(verbose_name='Texto del Enunciado')),
                ('es_verdadero', models.BooleanField(default=True, verbose_name='Es Verdadero')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enunciados', to='evaluaciones.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Enunciado',
                'verbose_name_plural': 'Enunciados',
                'ordering': ['numero'],
            },
        ),
    ]
