# Generated by Django 5.1.1 on 2026-01-06 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_intento', models.IntegerField(verbose_name='Número de Intento')),
                ('total_preguntas', models.IntegerField(verbose_name='Total de Preguntas')),
                ('preguntas_correctas', models.IntegerField(verbose_name='Preguntas Correctas')),
                ('preguntas_incorrectas', models.IntegerField(verbose_name='Preguntas Incorrectas')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota sobre 20')),
                ('aprobado', models.BooleanField(verbose_name='Aprobado')),
                ('tiempo_empleado', models.IntegerField(blank=True, null=True, verbose_name='Tiempo Empleado (segundos)')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Intento')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_examenes', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='evaluaciones.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Intento de Examen',
                'verbose_name_plural': 'Intentos de Exámenes',
                'ordering': ['-fecha_intento'],
                'unique_together': {('estudiante', 'examen', 'numero_intento')},
            },
        ),
    ]
