# Generated by Django 5.1.1 on 2026-01-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_intentoexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoexamen',
            name='cuenta_para_ranking',
            field=models.BooleanField(default=True, help_text='Solo el primer intento cuenta para el ranking', verbose_name='Cuenta para Ranking'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='es_premium',
            field=models.BooleanField(default=True, help_text='DEPRECATED: Este valor se determina automáticamente por materia.requiere_suscripcion', verbose_name='Requiere Suscripción Premium'),
        ),
    ]
