# Generated by Django 5.1.1 on 2026-01-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_intentoexamen_cuenta_para_ranking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='materia',
            new_name='tema',
        ),
    ]
