# Generated by Django 5.1.1 on 2026-02-22 21:10

from django.db import migrations
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_rename_materia_examen_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentoexamen',
            name='nota',
            field=django.db.models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota sobre 100'),
        ),
    ]
