# Generated by Django 5.1.1 on 2025-12-30 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verificacion_enviada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verificacion_reenvios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='verificacion_ventana_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CambioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_anterior', models.CharField(max_length=20)),
                ('rol_nuevo', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_rol_realizados', to=settings.AUTH_USER_MODEL)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_rol_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
