# Generated by Django 5.1.1 on 2026-01-01 14:44

import apps.cuentas.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_user_email_verificado_user_verificacion_enviada_en_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.cuentas.models.CustomUserManager()),
            ],
        ),
    ]
