# Generated by Django 5.1.1 on 2026-01-02 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proximo_repaso', models.DateTimeField(default=django.utils.timezone.now)),
                ('intervalo', models.IntegerField(default=0)),
                ('factor_facilidad', models.FloatField(default=2.5)),
                ('repeticiones', models.IntegerField(default=0)),
                ('ultimo_repaso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['proximo_repaso'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRepaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.IntegerField(choices=[(0, 'Otra vez (0-1 días)'), (1, 'Difícil (1-3 días)'), (2, 'Bien (3-7 días)'), (3, 'Fácil (7+ días)')])),
                ('fecha_repaso', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='flashcards.flashcard')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Repaso',
                'verbose_name_plural': 'Historiales de Repaso',
                'ordering': ['-fecha_repaso'],
            },
        ),
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mazos_flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mazo',
                'verbose_name_plural': 'Mazos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='mazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='flashcards.mazo'),
        ),
    ]
