# Generated by Django 5.1.1 on 2026-01-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazo',
            name='creado_por_admin',
            field=models.BooleanField(default=False, verbose_name='Creado por Admin'),
        ),
        migrations.AddField(
            model_name='mazo',
            name='es_premium',
            field=models.BooleanField(default=False, verbose_name='Es Premium'),
        ),
    ]
