# Generated by Django 5.1.1 on 2026-01-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_mazo_creado_por_admin_mazo_es_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mazo',
            name='creado_por_admin',
        ),
        migrations.RemoveField(
            model_name='mazo',
            name='es_premium',
        ),
    ]
