# Generated by Django 5.1.1 on 2026-02-11 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_mazo_materia'),
        ('materias_nueva', '0003_remove_materia_requiere_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mazo',
            name='tema',
        ),
        migrations.AddField(
            model_name='mazo',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mazos_flashcards', to='materias_nueva.materia', verbose_name='Materia'),
        ),
    ]
