# Generated by Django 5.1.1 on 2026-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias_nueva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['id'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AddField(
            model_name='materia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='materia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='requiere_suscripcion',
            field=models.BooleanField(default=False, help_text='Indica si esta materia requiere suscripción premium para acceder', verbose_name='Requiere Suscripción Premium'),
        ),
    ]
