# Generated by Django 5.1.1 on 2026-01-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias_nueva', '0002_alter_materia_options_materia_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='requiere_suscripcion',
        ),
    ]
