# Generated by Django 5.1.1 on 2026-01-28 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias_nueva', '0002_alter_materia_options_materia_created_at_and_more'),
        ('temas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['materia', 'id'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AddField(
            model_name='tema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tema',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='tema',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Tema'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='requiere_suscripcion',
            field=models.BooleanField(default=False, help_text='Indica si este tema requiere suscripción premium para acceder', verbose_name='Requiere Suscripción Premium'),
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('nombre', 'materia')},
        ),
    ]
