# Generated by Django 5.1.1 on 2026-01-07 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_examenes', models.IntegerField(default=0, verbose_name='Total de Exámenes Realizados')),
                ('promedio_general', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Promedio General')),
                ('total_aprobados', models.IntegerField(default=0, verbose_name='Exámenes Aprobados')),
                ('mejor_nota', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Mejor Nota')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Estadística de Estudiante',
                'verbose_name_plural': 'Estadísticas de Estudiantes',
                'ordering': ['-promedio_general', '-total_examenes'],
            },
        ),
    ]
