"""
Django settings for meetwin project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Cargar variables de entorno desde .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w(q(abp9d%t$c&f-(k0elcgxt7l))6(w=k45s7!bio))$)1!^9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.cuentas',
    'apps.contenido',
    'apps.evaluaciones',
    'apps.suscripciones',
    'apps.ranking',
    'apps.notificaciones',
    'apps.flashcards',
    'apps.flashcards_premium',
    'apps.usuarios',
    'apps.temas',
    'apps.materias_nueva',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meetwin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.suscripciones.context_processors.suscripcion_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'meetwin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'meetwin_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# Configuración de almacenamiento de archivos con Supabase
DEFAULT_FILE_STORAGE = 'meetwin.supabase_storage.SupabaseStorage'
STORAGES = {
    'default': {
        'BACKEND': 'meetwin.supabase_storage.SupabaseStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Fallback para desarrollo local (si Supabase no está disponible)
try:
    from meetwin.supabase_storage import SupabaseStorage
    SupabaseStorage()  # Verificar que Supabase esté configurado
    SUPABASE_ENABLED = True
except Exception as e:
    print(f"⚠ Advertencia: No se pudo conectar a Supabase: {e}")
    print("  Usando almacenamiento local como fallback")
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    SUPABASE_ENABLED = False

# URLs de Supabase para servir archivos públicos
SUPABASE_URL = os.environ.get('SUPABASE_URL', '').strip()
SUPABASE_BUCKET = os.environ.get('SUPABASE_BUCKET', 'media')

# Para desarrollo local, usar MEDIA_URL como antes
if not SUPABASE_ENABLED:
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    # Con Supabase, las URLs se generan dinámicamente
    MEDIA_URL = f"{SUPABASE_URL}/storage/v1/object/public/{SUPABASE_BUCKET}/"

AUTH_USER_MODEL = 'cuentas.User'

LOGIN_URL = 'cuentas:home'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST_USER = os.environ.get('EMAIL_USER', '').strip().strip('"\'')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD', '').strip().strip('"\'')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    # Intentar puerto 465 (SSL) si 587 (TLS) falla
    EMAIL_PORT = 465
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = True
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
    # Para debugging
    if DEBUG:
        print(f"✓ Email configurado: {EMAIL_HOST_USER}")
else:
    DEFAULT_FROM_EMAIL = 'no-reply@meetwin.local'
    print("⚠ Email NO configurado - Usando console backend")

EMAIL_VERIFICACION_MAX_AGE_SECONDS = 60 * 60 * 24
EMAIL_VERIFICACION_REENVIOS_MAX = 3
EMAIL_VERIFICACION_REENVIOS_VENTANA_SECONDS = 60 * 30

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
